### ISSUE TITLE
Generated native project should include a unit test for HelloAppEngine servlet (called HelloAppEngineTest)

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-tools-for-eclipse#129]
for the HelloAppEngine servlet, autogenerated by the wizard

**Comment by rdayal** [comment]
What is the actual task here?

**Comment by elharo** [comment]
The generated project should include a unit test for the generated servlet.

**Comment by akerekes** [comment]
Split into 2 issues one for native projects and [one for maven-based projects](#706).
