### ISSUE TITLE
Install the correct libraries in non-maven projects

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-tools-for-eclipse#328]
I assume these are the same three the AppEngine maven archetype adds:

![image](https://cloud.githubusercontent.com/assets/1005544/16558910/1211865c-41b7-11e6-9129-8a30588daf15.png)

This should be done in AppEngineSdkClasspathContainer. Note that servlet-api.jar and jstl-api.jar already come from the runtime.

**Comment by elharo** [comment]
2 of these are for testing. The third comes from the old App Engine Java SDK which we're replacing with gcloud.

**Comment by elharo** [comment]
Tentatively I think the tools api is in fact what we need. It's just renamed and repackaged between the cloud SDK and app engine Java SDK. We may still need to figure out where to get stubs and testing jar from though.

**Comment by elharo** [comment]
Why does gcloud not include jstl but maven projects do have it?

$ ls /Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/shared
LICENSE					jsp
appengine-local-runtime-shared.jar	jsp-api.jar
appengine-remote-api.jar		servlet-api.jar
el-api.jar

**Comment by briandealwis** [comment]
FWIW, it's not included in the `appengine-java-sdk-*` bundles

**Comment by elharo** [comment]
@ludoch says we should not include the stubs jar. We may need to remove this from the maven dependencies or mark it as runtime only in the pom.xml.

**Comment by briandealwis** [comment]
I believe the stubs are a test-only dependency in Maven.

**Comment by elharo** [comment]
Yes, but I don't think they should be even that. I'm not sure we need them at all, but I'll need to try removing them and see if anything breaks. It should only be used by the local dev server that we execute as a shell process through gcloud so it shouldn't need to be in our classpath.

**Comment by ludoch** [comment]
What makes you "believe the stubs are a test-only dependency in Maven" ?

**Comment by elharo** [comment]
That's how they're currently listed in the pom.xml:

https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/blob/master/appengine-skeleton-archetype/src/main/resources/archetype-resources/pom.xml

Now whether they actually need to be there at all is the open question.

**Comment by elharo** [comment]
The stubs do appear to be a dependency of the guestbook archetype in maven. After removing that dependency:

Running com.google.guest.GuestbookServletTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.906 sec
Running com.google.guest.SignGuestbookServletTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.003 sec <<< FAILURE!
testDoPost(com.google.guest.SignGuestbookServletTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/appengine/api/datastore/dev/LocalDatastoreService$AutoIdAllocationPolicy
	at com.google.appengine.tools.development.testing.LocalDatastoreServiceTestConfig.<init>(LocalDatastoreServiceTestConfig.java:25)
	at com.google.guest.SignGuestbookServletTest.<init>(SignGuestbookServletTest.java:53)
	at sun.re

**Comment by elharo** [comment]
waiting @patflynn 's discussion document

**Comment by elharo** [comment]
We've decided not to include more than the servlet and jsp libraries by default.

**Comment by geography-tuition** [comment]
its pleasure to read a beautiful blog. I’m not sure where you are getting your info, but great topic. I need to spend some time learning more or understanding more. Thanks for excellent information I was looking for this information for my mission.  Feel free to visit my website  <a href= https://smiletutor.sg/geography-tuition>geography tuition</a> with fee free.
