### ISSUE TITLE
Establish lifetime for login credentials

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-tools-for-eclipse#460]
E.g. make sure they expire after 4 hours. We may be able to specify a lifetime when we request the credentials from the server. It may be that the server sets a reasonable lifetime and this is a noop for us, but let's make sure.

**Comment by akerekes** [comment]
Eventually I'd rather let the user control this TTL (modulo the server side imposed restrictions) with a reasonable default (4 hours/8 hours).

**Comment by patflynn** [comment]
login library stores a refresh token which never expires.  Aren't you using
that?

**Comment by elharo** [comment]
I don't think we want infinite lifetime. 24 hours at the outside.

**Comment by briandealwis** [comment]
Perhaps we should punt on storing credentials and just use `gcloud`'s credentials instead?

**Comment by patflynn** [comment]
gcloud, the login library that IJ uses, and CT4VS store the refresh token.
I don't think we should change this behavior for Eclipse.

There were discussions a long time ago about using the gcloud creds but for
various reasons which we should discuss offline, this was not done.
