### ISSUE TITLE
Cannot launch multiple-module/service apps

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/cloud-tools-for-eclipse#498]
#474 configured the launch of `dev_appserver` to only start a single module instances as the stock JDT _socket listener_ `IVMConnector` only accepts only the first connection.  This behaviour will be a limitation for debugging apps with multiple services.  We should extend or write a new `IVMConnector` that continues to accept new incoming connections from debug JVMs, allowing a launch to connect to multiple JVMs.

**Comment by briandealwis** [comment]
#473

**Comment by briandealwis** [comment]
Work in progress: https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/tree/wip-498

Turns out the underlying Eclipse JDT/Debug [doesn't support multiple connections on a listening socket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=499385).  Although it's straight-forward to fix, we're stuck with the status quo and need a workaround.

It seems the `max_module_instances` may still be useful to keep as hitting a breakpoint and then receiving another connection causes dev_appserver to launch a new instance.  So you end up with a number of instances.

It would also be nice to leverage any information from the launched JVMs to create meaningful labels.  Ideally that would include the service name.

**Comment by briandealwis** [comment]
In creating the Eclipse bug report, I realized that rather than connection argument _multiple_:

> It might be more flexible to use "count" with an integer, defaulting to 1, with 0 being unlimited

That would allow a launch to accept up to 5 connections, but no more.  And _count = 1_ is the current behaviour.

**Comment by chanseokoh** [comment]
@briandealwis I am trying to understand this issue: with the fix #609, it looks like we support launching multiple modules (or JVM?) for local debug run. You also said just above that

> It seems the max_module_instances may still be useful to keep as hitting a breakpoint and then receiving another connection causes dev_appserver to launch a new instance. So you end up with a number of instances.

and currently, we do limit the number of modules to 1:

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java#L177

So, is it that we have an infrastructure set up for accepting multiple connections (JVMs?) in local debug run, but we aren't really allowing multiple connections yet?

**Comment by briandealwis** [comment]
> So, is it that we have an infrastructure set up for accepting multiple connections (JVMs?) in local debug run, but we aren't really allowing multiple connections yet? 

That's right: I restored it in #657 as you get some confusing behaviour when hitting a breakpoint.  If you're using a browser to invoke the endpoints, browsers will oftentimes test-fetch the URL; since the existing request hasn't completed, the `dev_appserver` launches a new JVM to handle the test-fetch.   We need to provide some UI to allow the user to change the max-instances.

**Comment by chanseokoh** [comment]
Got it, thanks.
