### ISSUE TITLE
Should wizard put project ID in appengine-web.xml?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-tools-for-eclipse#520]
@patflynn keeps telling me that the project ID should not be in appengine-web.xml and instead supplied at deploy time. However the App Engine docs don't agree:

https://cloud.google.com/appengine/docs/java/config/appref

In fact, they state that this element is "required", not merely allowed. OTOH the schema indicates it's optional:

    <xs:element type="xs:string" name="application" minOccurs="0"/>

The docs may be out of date. Resolve this (if necessary by fixing the docs)

If we indeed don't want to include the project ID, then we should pull it out of the wizard dialog for creating new projects.

**Comment by briandealwis** [comment]
> If we indeed don't want to include the project ID, then we should pull it out of the wizard dialog for creating new projects.

Or maybe find a different way to specify it?  It can be used for auto-populating the deploy dialog.

**Comment by elharo** [comment]
fixed. we don't include it.
