### ISSUE TITLE
Improve server-start detection to mark server a STATE_STARTED

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/cloud-tools-for-eclipse#556]
`LocalAppEngineServerBehaviour` uses an `appengine-plugins-core` `ProcessStartedListener`  to set the server's state to `STATE_STARTED` (in `LocalAppEngineStartListener`). This listener is fired once `appengine-plugins-core` has launched the process, but does not necessarily indicate that the server was actually started (e.g., could be delayed, could have errored out).  We should not set `STATE_STARTED` until we're able to probe the deserver's API port. An alternative is to push that responsibility should be to `appengine-plugins-core`.

**Comment by chanseokoh** [comment]
This will be tricky to achieve, unless we do periodic polling inside `ProcessStartedListener`, which may not be a bad idea.

**Comment by briandealwis** [comment]
My idea was to start a job that periodically polls on the dev server's api port.

**Comment by briandealwis** [comment]
Another idea is to scan the log for "GET /_ah/warmup HTTP/1.1"

**Comment by briandealwis** [comment]
@ludoch pointed to the gcloud Maven plugin which takes the log scanning approach looking for particular strings:

https://github.com/GoogleCloudPlatform/gcloud-maven-plugin/blob/174d2e7277e779c095396b86aca759aa91adf033/src/main/java/com/google/appengine/gcloudapp/AbstractGcloudMojo.java#L412

**Comment by briandealwis** [comment]
Other server types register a _ping_ thread that eventually times out.
