### ISSUE TITLE
[Windows] Eclipse STOP button does not stop server process

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/cloud-tools-for-eclipse#597]
Hello,

it seems that the STOP button in Eclipse Server view
![image](https://cloud.githubusercontent.com/assets/12278553/17846902/7c6d3266-684b-11e6-91dd-de84628581e0.png)

Does not truly kill the server process.

Here you can see that I used the stop button
![image](https://cloud.githubusercontent.com/assets/12278553/17846926/9ac9736e-684b-11e6-82b2-7a7835944e23.png)

But the inside the Debug the process is still running
![image](https://cloud.githubusercontent.com/assets/12278553/17846936/ac3c27fe-684b-11e6-92eb-32be4f7f42aa.png)

and even inside the Task Manager the Java process is running
![image](https://cloud.githubusercontent.com/assets/12278553/17846952/bc622b7e-684b-11e6-94b3-ba56f52576d5.png)

Also... 
If I use the Terminate button on the running process
![image](https://cloud.githubusercontent.com/assets/12278553/17846976/d33d184a-684b-11e6-942a-30872da45d53.png)

The Java process still is not killed
![image](https://cloud.githubusercontent.com/assets/12278553/17846982/df3fa040-684b-11e6-8880-ebcb56833800.png)

I need to explicitly kill it from the Task Manager

**Comment by briandealwis** [comment]
Same as #516

**Comment by briandealwis** [comment]
Reopening — the zombie process is a separate problem.

**Comment by NicolaSpreafico** [comment]
Hello,
here is my current configuration

```
Version: Neon.1a Release (4.6.1)
Build id: 20161007-1200

Google Cloud Platform for Eclipse 4.5 and 4.6	0.1.0.201612082156
com.google.cloud.tools.eclipse.suite.e45.feature.feature.group	Google, Inc.
```

I just tried to stop the dev-server using  both the STOP button on the server and inside the debug section, and with both of them the python processes that can be viewed from the Task Manager has been killed. It is not an instant operation (it took about 2-3 seconds in order to see the python process go away from the processes list) but at the end it works.

I also tried the Restart function (instead of doing first Stop and the Launch) and it seems to works as well

**Comment by chanseokoh** [comment]
Thanks for the update @NicolaSpreafico. Good to know it works well in your env.

**Comment by NicolaSpreafico** [comment]
Found a particular scenario when the flow does not work.

I launch the server in Debug Mode and I make a change in the code.
The _Hot Code Replace_ fails with this error
![image](https://cloud.githubusercontent.com/assets/12278553/21540271/7e8fd3be-cdae-11e6-850e-98926aab3bd8.png)

If I hit "_Continue_" the server continues running w/o the modification I made

If I hit "_Disconnect_" the server is disconnected but the java/python processes are still visibile in Task Manager
![image](https://cloud.githubusercontent.com/assets/12278553/21540326/d85f0400-cdae-11e6-877b-f08b439f8770.png)
![image](https://cloud.githubusercontent.com/assets/12278553/21540333/dfc60bc6-cdae-11e6-827a-e709696f5067.png)
