### ISSUE TITLE
Should terminating a launch also stop the server?

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/cloud-tools-for-eclipse#620]
Terminating the launch doesn't stop the server instance.  Should it?

Minimal code I can find to do this, though I suspect there must be something else available.
```
    getLaunchManager().addLaunchListener(new ILaunchesListener2() {

      @Override
      public void launchesRemoved(ILaunch[] launches) {}

      @Override
      public void launchesChanged(ILaunch[] launches) {}

      @Override
      public void launchesAdded(ILaunch[] launches) {}

      @Override
      public void launchesTerminated(ILaunch[] launches) {
        for (ILaunch terminated : launches) {
          if (terminated == launch) {
            server.stop(true);
          }
        }
      }
    });
```

**Comment by elharo** [comment]
I suspect it should, but what exactly do you mean by terminating the launch?

**Comment by briandealwis** [comment]
If you terminate the _launch_ object in the _Debug_ view:

![screen shot 2016-08-29 at 9 18 18 am](https://cloud.githubusercontent.com/assets/202851/18052687/c8543a5c-6dc9-11e6-88f8-d5bbcd888d29.PNG)

the server remains in the _started_ state:

![screen shot 2016-08-29 at 9 19 07 am](https://cloud.githubusercontent.com/assets/202851/18052696/d1d2de1c-6dc9-11e6-83ac-8dfdc0f40c02.PNG)

I can't think of a reason why this would be useful.  I took a quick look at GPE and didn't see any obvious hooks in its WTP support, but I haven't yet tested.

**Comment by elharo** [comment]
Seems reasonable.

**Comment by chanseokoh** [comment]
@briandealwis I think #664 closes this?

**Comment by briandealwis** [comment]
I knew there was another issue open, but couldn't find it!
