### ISSUE TITLE
Locked up Eclipse on "Deploy to App Engine"

### ISSUE THREAD

**Issue by salamanders** [GoogleCloudPlatform/cloud-tools-for-eclipse#630]
OSX.  Tried the new plugin.  Froze up when deploying to GAE after the uploaded files step.  A Cancel request didn't cancel.  Eventually had to force-quit Eclipse.

**Comment by akerekes** [comment]
@salamanders Can you share the log to see how for it got? Did Eclipse become unresponsive? Could you click the Cancel button? How long have you waited before trying to cancel the deploy?
What's the OS, Java, Eclipse and gcloud version you use? Can you share a project that we can use to reproduce the issue?

**Comment by chanseokoh** [comment]
I hit a similar problem once before, possibly the same one. In my case, the gcloud deploy process didn't make progress at least for 5 minutes (it was a transient error), and I force-quit Eclipse to clear the Eclipse job.

@salamanders [Our plugin doesn't honor the cancel request once the deployment process starts](https://github.com/GoogleCloudPlatform/cloud-tools-for-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/AppEngineProjectDeployer.java#L28) (#439), so if for whatever reason the deploy process locks up, say, for 5 minutes, you cannot cancel the job for 5 minutes (i.e, until the process terminates). Clicking the cancel button will do nothing but show the message "Cancel Requested":

![deploy_cancel](https://cloud.githubusercontent.com/assets/10523105/18088610/86d6994c-6e89-11e6-8b50-0e6102c82d51.png)

**Comment by chanseokoh** [comment]
Forgot to add this:

If this happens, we cannot even quit Eclipse in a normal way. When trying to close Eclipse, users will be present with the dialog below. The dialog doesn't have a 'X' button, and its 'Cancel' button is also grayed out, so users become completely stuck. At this point, users have to kill the Eclipse java process manually.

![lock-up](https://cloud.githubusercontent.com/assets/10523105/18089675/17db67ba-6e8f-11e6-96d3-72b98ecf7440.png)

**Comment by briandealwis** [comment]
Oh that's not good.  That suggests that we're somehow blocking the SWT/UI thread.  Could you take a stack trace (`jstack -p PID`)?  And you should be able to kill the `gcloud` command.

**Comment by salamanders** [comment]
That matches my experience - ignores cancel request, can't close eclipse.  I lost an edit.

**Comment by briandealwis** [comment]
I misread @chanseokoh's comment — the UI isn't unresponsive, but just blocked.
