### ISSUE TITLE
Shorten deploy prompt message

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-tools-for-eclipse#634]
Right now it's so long, it can appear off screen:

![image](https://cloud.githubusercontent.com/assets/1005544/18092376/0c332a1e-6e9a-11e6-8046-8087dae5fc69.png)

perhaps "During deploy you can provide a project ID that will be used instead of the project ID set on this page" or even just "Ask for project ID when deploying"

**Comment by elharo** [comment]
also delete "Always" from "Always prompt"

**Comment by akerekes** [comment]
Fixed by #636
