### ISSUE TITLE
Support domain names in project IDs

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-tools-for-eclipse#666]
I found a project ID in the wild, in an appengine-web.xml file, of the form:

domain.com:projectname

1. Figure out if this is what's actually needed to deploy such an app engine app.
2. If so, make sure our project ID validator allows this. 
3. If necessary, update public docs about project IDs to explain this

**Comment by elharo** [comment]
It occurs to me we should probably move the project ID validator logic into appengine-plugins-core. It's in no way eclipse specific.

**Comment by elharo** [comment]
When I moved this to  appengine-plugins-core, I removed the check that allows empty strings as legal IDs. We'll need to provide that at a higher level in the UI so entering the project ID in the new application wizard is still optional. (I.e. don't try to validate empty string.)

**Comment by chanseokoh** [comment]
I'm guessing the first part before `:` is an organization name (which may be wrong of course) as seen below. It may not have to take the form of a domain?

![selection_010](https://cloud.githubusercontent.com/assets/10523105/18593742/d6cb6ef8-7c0a-11e6-913d-19dfe336d404.png)

![selection_011](https://cloud.githubusercontent.com/assets/10523105/18593802/11182dee-7c0b-11e6-998d-6b2dfb5f34be.png)

**Comment by elharo** [comment]
fixed by #735
