### ISSUE TITLE
Fishfood: New project dialog: Not clear what fields are required vs optional

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/cloud-tools-for-eclipse#670]
<img width="537" alt="screen shot 2016-09-06 at 10 24 36 am" src="https://cloud.githubusercontent.com/assets/1758462/18284961/f8158f90-7420-11e6-91f4-021d8c68b7ce.png">

Java Package should also be labelled (Optional)

**Comment by elharo** [comment]
Package is not technically required but it is very strongly recommended for any non-toy Java app.

**Comment by YnR** [comment]
OK, I recommend not closing this bug unless we have agreed how to modify the UX, if at all. I am interpreting this as "I don't think the change is required", is that correct?

**Comment by elharo** [comment]
Yes, that's correct.

**Comment by YnR** [comment]
The difference of treatment between two optional fields bothers me. I can believe that the Java developer will know that it is better to have it, but since the Finish button does not get activated until the right data is in the form, I feel we should help explain what is required here.
