### ISSUE TITLE
Where did our new project wizards go?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-tools-for-eclipse#679]

**Comment by briandealwis** [comment]
What are you seeing?  They still show up for me and work fine.  Sounds suspiciously like the `.newproject` bundles aren't being loaded, which usually indicates a problem with dependencies. Assuming this is in your local IDE, try using the _Validate Plug-ins_ from the launch configuration.

**Comment by elharo** [comment]
Appears to have been a problem with some changes I was making in appengine-plugins-core in the same workspace.
