### ISSUE TITLE
The Dark theme separators are white for 'App Engine Deployment' dialog.

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/cloud-tools-for-eclipse#717]
The Dark theme separators are white for 'App Engine Deployment' dialog. Something looks off when they are like that. 

![screen shot 2016-09-19 at 4 34 09 pm](https://cloud.githubusercontent.com/assets/1326504/18652389/ffb2ca4a-7e86-11e6-82d4-db7ffd83a809.png)

**Comment by elharo** [comment]
@akerekes Any idea what's going on here?
